// Frontend-Oriented/frontend/frontend-angular/src/components/ui/success-notification/success-notification.component.ts
import { Component, Input, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * Success notification component
 */
@Component({
  selector: 'app-success-notification',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './success-notification.component.html',
  styleUrl: './success-notification.component.css'
})
export class SuccessNotificationComponent implements OnInit, OnDestroy {
  @Input() message: string = '';
  @Input() onClose?: () => void;
  @Input() autoClose: boolean = true;
  @Input() duration: number = 3000;

  private timer?: ReturnType<typeof setTimeout>;

  ngOnInit() {
    if (this.autoClose && this.onClose) {
      this.timer = setTimeout(() => {
        this.onClose?.();
      }, this.duration);
    }
  }

  ngOnDestroy() {
    if (this.timer) {
      clearTimeout(this.timer);
    }
  }
}

// Frontend-Oriented/frontend/fronntend-react/src/components/ui/SuccessNotification.tsx
import React, { useEffect } from 'react';
import './SuccessNotification.css';

interface SuccessNotificationProps {
  message: string;
  onClose?: () => void;
  autoClose?: boolean;
  duration?: number;
}

/**
 * Success notification component
 */
export const SuccessNotification: React.FC<SuccessNotificationProps> = ({
  message,
  onClose,
  autoClose = true,
  duration = 3000,
}) => {
  useEffect(() => {
    if (autoClose && onClose) {
      const timer = setTimeout(() => {
        onClose();
      }, duration);
      return () => clearTimeout(timer);
    }
  }, [autoClose, duration, onClose]);

  return (
    <div className="success-notification" data-testid="success-notification">
      <span className="success-icon">✓</span>
      <span className="success-message">{message}</span>
      {onClose && (
        <button className="success-close-button" onClick={onClose}>
          ×
        </button>
      )}
    </div>
  );
};
