// Backend-Oriented/frontend/frontend-angular/src/components/navigation/navigation.component.ts
import { Component, OnDestroy, ElementRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { Subject, Subscription, debounceTime, distinctUntilChanged, switchMap, of } from 'rxjs';
import { SearchService, SearchResult } from '../../services/search.service';

/**
 * Navigation component with global search bar
 */
@Component({
  selector: 'app-navigation',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  templateUrl: './navigation.component.html',
  styleUrl: './navigation.component.css'
})
export class NavigationComponent implements OnDestroy {
  @ViewChild('searchContainer') searchContainer!: ElementRef;

  searchQuery = '';
  searchResults: SearchResult | null = null;
  showResults = false;
  searching = false;

  private searchSubject = new Subject<string>();
  private searchSubscription: Subscription;

  constructor(
    public router: Router,
    private searchService: SearchService
  ) {
    this.searchSubscription = this.searchSubject.pipe(
      debounceTime(300),
      distinctUntilChanged(),
      switchMap(query => {
        if (!query.trim()) {
          this.searchResults = null;
          this.showResults = false;
          return of(null);
        }
        this.searching = true;
        return this.searchService.search(query.trim());
      })
    ).subscribe({
      next: (results) => {
        if (results) {
          this.searchResults = results;
          this.showResults = true;
        }
        this.searching = false;
      },
      error: () => {
        this.searching = false;
        this.searchResults = null;
      }
    });
  }

  onSearchInput() {
    this.searchSubject.next(this.searchQuery);
  }

  onSearchFocus() {
    if (this.searchResults) {
      this.showResults = true;
    }
  }

  navigateTo(path: string) {
    this.showResults = false;
    this.searchQuery = '';
    this.router.navigate([path]);
  }

  highlightMatch(text: string, query: string): string {
    if (!query.trim()) return text;
    const escaped = query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`(${escaped})`, 'gi');
    return text.replace(regex, '<mark>$1</mark>');
  }

  get totalResults(): number {
    if (!this.searchResults) return 0;
    return this.searchResults.scenarios.length + this.searchResults.entities.length;
  }

  onDocumentClick(event: MouseEvent) {
    if (this.searchContainer && !this.searchContainer.nativeElement.contains(event.target)) {
      this.showResults = false;
    }
  }

  ngOnDestroy() {
    this.searchSubscription.unsubscribe();
  }
}

<nav class="navigation" (document:click)="onDocumentClick($event)">
  <div class="nav-container">
    <a routerLink="/" class="nav-brand">Scenario Builder</a>

    <div class="nav-search" #searchContainer>
      <input
        type="text"
        placeholder="Search scenarios and entities..."
        [(ngModel)]="searchQuery"
        (ngModelChange)="onSearchInput()"
        (focus)="onSearchFocus()"
        class="search-input" />
      @if (searching) {
        <span class="search-spinner"></span>
      }

      @if (showResults && searchResults) {
        <div class="search-dropdown">
          @if (totalResults === 0) {
            <div class="search-no-results">No results found</div>
          } @else {
            @if (searchResults.scenarios.length > 0) {
              <div class="search-section">
                <div class="search-section-title">Scenarios</div>
                @for (s of searchResults.scenarios; track s.id) {
                  <div class="search-result-item" (click)="navigateTo('/scenarios/' + s.id)">
                    <div class="search-result-name" [innerHTML]="highlightMatch(s.name, searchQuery)"></div>
                    @if (s.description) {
                      <div class="search-result-detail" [innerHTML]="highlightMatch(s.description, searchQuery)"></div>
                    }
                  </div>
                }
              </div>
            }
            @if (searchResults.entities.length > 0) {
              <div class="search-section">
                <div class="search-section-title">Entities</div>
                @for (e of searchResults.entities; track e.id) {
                  <div class="search-result-item" (click)="navigateTo('/scenarios/' + e.scenarioId)">
                    <div class="search-result-name" [innerHTML]="highlightMatch(e.name, searchQuery)"></div>
                    <div class="search-result-detail">{{ e.type }} &middot; {{ e.taskForce }}</div>
                  </div>
                }
              </div>
            }
          }
        </div>
      }
    </div>

    <div class="nav-links">
      <a routerLink="/scenarios"
         routerLinkActive="active"
         [routerLinkActiveOptions]="{exact: false}">
        Scenarios
      </a>
    </div>
  </div>
</nav>

// Backend-Oriented/frontend/fronntend-react/src/components/Navigation.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { searchService, SearchResult } from '../services/searchService';
import './Navigation.css';

/**
 * Navigation component with global search bar
 */
export const Navigation: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<SearchResult | null>(null);
  const [showResults, setShowResults] = useState(false);
  const [searching, setSearching] = useState(false);
  const searchRef = useRef<HTMLDivElement>(null);
  const debounceRef = useRef<ReturnType<typeof setTimeout>>();

  useEffect(() => {
    if (!searchQuery.trim()) {
      setSearchResults(null);
      setShowResults(false);
      return;
    }

    // Debounce search
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(async () => {
      setSearching(true);
      try {
        const results = await searchService.search(searchQuery.trim());
        setSearchResults(results);
        setShowResults(true);
      } catch {
        setSearchResults(null);
      } finally {
        setSearching(false);
      }
    }, 300);

    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, [searchQuery]);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (searchRef.current && !searchRef.current.contains(e.target as Node)) {
        setShowResults(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Close dropdown on navigation
  useEffect(() => {
    setShowResults(false);
    setSearchQuery('');
  }, [location.pathname]);

  const highlightMatch = (text: string, query: string) => {
    if (!query.trim()) return text;
    const regex = new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'gi');
    const parts = text.split(regex);
    return parts.map((part, i) =>
      regex.test(part) ? <mark key={i}>{part}</mark> : part
    );
  };

  const totalResults = searchResults
    ? searchResults.scenarios.length + searchResults.entities.length
    : 0;

  return (
    <nav className="navigation">
      <div className="nav-container">
        <Link to="/" className="nav-brand">
          Scenario Builder
        </Link>

        <div className="nav-search" ref={searchRef}>
          <input
            type="text"
            placeholder="Search scenarios and entities..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            onFocus={() => searchResults && setShowResults(true)}
            className="search-input"
          />
          {searching && <span className="search-spinner" />}

          {showResults && searchResults && (
            <div className="search-dropdown">
              {totalResults === 0 ? (
                <div className="search-no-results">No results found</div>
              ) : (
                <>
                  {searchResults.scenarios.length > 0 && (
                    <div className="search-section">
                      <div className="search-section-title">Scenarios</div>
                      {searchResults.scenarios.map((s) => (
                        <div
                          key={s.id}
                          className="search-result-item"
                          onClick={() => navigate(`/scenarios/${s.id}`)}
                        >
                          <div className="search-result-name">
                            {highlightMatch(s.name, searchQuery)}
                          </div>
                          {s.description && (
                            <div className="search-result-detail">
                              {highlightMatch(s.description, searchQuery)}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                  {searchResults.entities.length > 0 && (
                    <div className="search-section">
                      <div className="search-section-title">Entities</div>
                      {searchResults.entities.map((e) => (
                        <div
                          key={e.id}
                          className="search-result-item"
                          onClick={() => navigate(`/scenarios/${e.scenarioId}`)}
                        >
                          <div className="search-result-name">
                            {highlightMatch(e.name, searchQuery)}
                          </div>
                          <div className="search-result-detail">
                            {e.type} &middot; {e.taskForce}
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </>
              )}
            </div>
          )}
        </div>

        <div className="nav-links">
          <Link
            to="/scenarios"
            className={`nav-link ${location.pathname.startsWith('/scenarios') ? 'active' : ''}`}
          >
            Scenarios
          </Link>
        </div>
      </div>
    </nav>
  );
};
