// Backend-Oriented/frontend/fronntend-react/src/components/guards/EntityGuard.tsx
import React from 'react';
import { useParams, Navigate } from 'react-router-dom';

/**
 * Guard component to validate scenario and entity ID format
 */
export const EntityGuard: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { scenarioId, entityId } = useParams<{ scenarioId?: string; entityId?: string }>();
  
  if (!scenarioId || scenarioId.trim() === '') {
    return <Navigate to="/scenarios" replace />;
  }
  
  if (entityId && entityId.trim() === '') {
    return <Navigate to={`/scenarios/${scenarioId}`} replace />;
  }
  
  return <>{children}</>;
};

// Frontend-Oriented/frontend/frontend-angular/src/app/guards/entity.guard.ts
import { inject } from '@angular/core';
import { Router, ActivatedRouteSnapshot, CanActivateFn } from '@angular/router';

export const entityGuard: CanActivateFn = (route: ActivatedRouteSnapshot) => {
  const router = inject(Router);
  const scenarioId = route.paramMap.get('scenarioId');
  const entityId = route.paramMap.get('entityId');
  
  if (!scenarioId || scenarioId.trim() === '') {
    router.navigate(['/scenarios']);
    return false;
  }
  
  if (entityId && entityId.trim() === '') {
    router.navigate(['/scenarios', scenarioId]);
    return false;
  }
  
  return true;
};
